# Generated by Django 4.0.1 on 2022-02-02 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_examdetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 2)),
        ),
    ]
