# Generated by Django 4.0.1 on 2022-02-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_exam_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='first_name',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
