# Generated by Django 4.0.1 on 2022-02-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_exam_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='first_name',
        ),
    ]
